import '@/app/globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { getSession } from "@/auth";
import { Web3Provider } from '@/components/providers';
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Student Identity App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <ToastContainer />
          <NextAuthWrapper session={session}>
            <Web3Provider>
              {children}
            </Web3Provider>
          </NextAuthWrapper>
        </Suspense>
      </body>
    </html>
  );
}
