import "@/app/styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { getAuthSession } from "@/auth";
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import React from "react";
import Loader from "./loader";
import { Web3Provider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Student Identity App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </head>
      <body className={`${inter.className} bg-black`}>
        <React.StrictMode>
          <ToastContainer />
          <NextAuthWrapper session={session}>
            <Web3Provider>
              <Suspense fallback={<Loader />}>{children}</Suspense>
            </Web3Provider>
          </NextAuthWrapper>
        </React.StrictMode>
      </body>
    </html>
  );
}
