import '@/app/styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { getSession } from "@/auth";
import { Web3Provider } from '@/components/providers';
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from 'react';
import React from 'react';
import Loader from './loader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Student Identity App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/public/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </head>
      <body className={inter.className}>
        <React.StrictMode>
          <ToastContainer />
          <NextAuthWrapper session={session}>
            <Web3Provider>
              <Suspense fallback={<Loader />}>
                {children}
              </Suspense>
            </Web3Provider>
          </NextAuthWrapper>
        </React.StrictMode>
      </body>
    </html>
  );
}
